# KdTree

In [1]:
import numpy as np

In [2]:
from scipy.spatial import cKDTree

In [3]:
np.random.seed(0)

In [4]:
X=np.random.random((1000,3))

In [5]:
X.shape

(1000, 3)

In [6]:
X

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       ...,
       [0.47521403, 0.28729288, 0.87968154],
       [0.28492705, 0.94168707, 0.54613275],
       [0.32361371, 0.81354502, 0.69740038]])

In [7]:
kdt=cKDTree(X)

In [9]:
kdt?

In [10]:
%timeit kdt.query(X,k=2)

1.39 ms ± 11.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
kdt.query?

In [12]:
dd, ii = kdt.query(X,k=2)

In [13]:
dd

array([[0.        , 0.12410523],
       [0.        , 0.09333137],
       [0.        , 0.03246973],
       ...,
       [0.        , 0.03637539],
       [0.        , 0.07151994],
       [0.        , 0.0313286 ]])

In [14]:
ii


array([[  0, 225],
       [  1, 692],
       [  2, 622],
       ...,
       [997, 784],
       [998, 336],
       [999, 352]])