# Chapter 7 : Application PCA

In [1]:
import numpy as np
from sklearn.decomposition import PCA

/Users/dagoret/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
X = np.random.normal(size=(100,3))

In [3]:
X.shape

(100, 3)

In [4]:
R=np.random.random((3,10))

In [5]:
X=np.dot(X,R)

In [6]:
X.shape

(100, 10)

## PCA

In [7]:
pca=PCA(n_components=4)

### Fit PCA

In [8]:
pca.fit(X)

PCA(n_components=4)

### Projection of X

In [9]:
comp=pca.transform(X)   

In [10]:
mean=pca.mean_

In [11]:
mean

array([ 0.00488502, -0.01817084,  0.01215837,  0.07004671,  0.01042822,
       -0.038126  ,  0.03558488,  0.02105986,  0.03960498,  0.03366678])

In [12]:
mean.shape

(10,)

In [13]:
components = pca.components_

In [14]:
components

array([[ 0.1597613 ,  0.26289894,  0.46607826,  0.36965904,  0.38161871,
         0.32035655,  0.33984704,  0.3173111 ,  0.22363326,  0.1924276 ],
       [-0.01078196,  0.27317094,  0.19235011, -0.65017376,  0.11704319,
         0.51849313, -0.1829869 ,  0.11836158, -0.21453746, -0.29913656],
       [-0.19819583, -0.33538138,  0.19055775, -0.33506751,  0.02115157,
        -0.38282995,  0.04605212,  0.63023912,  0.36426677, -0.14365466],
       [ 0.12950346,  0.22987746, -0.45857669,  0.06256093, -0.44263383,
         0.12216343,  0.44601828,  0.49614197, -0.22223397, -0.10417795]])

In [15]:
components.shape

(4, 10)

In [16]:
var=pca.explained_variance_

In [17]:
var

array([7.47449015e+00, 8.43054142e-01, 2.92918401e-01, 6.33321695e-32])