# Chapter 7 : Application PCA

In [1]:
import numpy as np
from sklearn.decomposition import PCA

In [2]:
X = np.random.normal(size=(100,3))

In [5]:
X.shape

(100, 3)

In [4]:
R=np.random.random((3,10))

In [6]:
X=np.dot(X,R)

In [7]:
X.shape

(100, 10)

## PCA

In [8]:
pca=PCA(n_components=4)

### Fit PCA

In [9]:
pca.fit(X)

PCA(n_components=4)

### Projection of X

In [10]:
comp=pca.transform(X)   

In [11]:
mean=pca.mean_

In [12]:
mean

array([0.07122248, 0.14796572, 0.07986965, 0.17641571, 0.15844472,
       0.02725362, 0.08066086, 0.00874576, 0.17563908, 0.08451817])

In [15]:
mean.shape

(10,)

In [13]:
components = pca.components_

In [14]:
components

array([[-0.39950305, -0.24175383, -0.29899775, -0.49701629, -0.38996732,
        -0.2895286 , -0.23072533, -0.21967522, -0.28314789, -0.16721877],
       [-0.43163114,  0.24616928,  0.13593693, -0.06518438,  0.36467234,
        -0.1399319 , -0.02488236, -0.61376972,  0.42647423,  0.13633733],
       [-0.01154518,  0.40857471, -0.44786823,  0.25621649, -0.24511689,
        -0.58399493,  0.09534077,  0.25087784,  0.27879472,  0.12574637],
       [-0.19069417, -0.33927842,  0.18905532,  0.43995198, -0.62618233,
         0.20267638, -0.09310009, -0.13589914,  0.39592748,  0.0463619 ]])

In [16]:
components.shape

(4, 10)

In [17]:
var=pca.explained_variance_

In [18]:
var

array([7.95571655e+00, 8.91777975e-01, 3.65443685e-01, 3.85111235e-32])