# Chapter 7 : SVD decomposition

In [17]:
import numpy as np

In [18]:
X=np.random.random((100,3))

In [19]:
CX=np.dot(X.T,X)

In [20]:
U,Sdiag,VT=np.linalg.svd(X,full_matrices=False)

In [21]:
CYDiag,R=np.linalg.eigh(CX)

In [22]:
Sdiag

array([8.95362504, 3.02635145, 2.5944632 ])

In [23]:
CYDiag

array([ 6.73123931,  9.15880309, 80.16740132])

In [24]:
VT

array([[-0.62324095, -0.55705459, -0.54887239],
       [ 0.66715635, -0.74491614, -0.00153079],
       [ 0.40801117,  0.36713776, -0.83590475]])

In [25]:
np.allclose(CYDiag,Sdiag[::-1]**2)

True

In [26]:
VT[::-1].T/R

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])